### ISSUE TITLE
Docker Images optimization & consistency

### ISSUE THREAD

**Issue by demon-xxi** [pintostack/core#8]
Need to refactor some of the images to have same OS and/or java version as well as keep image size minimal.

- Use same minimal or base linux image where possible.
- Use Java 8 by default as 7 is not well supported any more.
- Execute `bootstrap.sh` using `ENTRYPOINT` command in all images consistently.

**Comment by yvlasov** [comment]
Yuri Gubin made a good work on migrating PS to docker so now we have a several dockers published with same parent images, so it looks to me like very optimal solution.

**Comment by yvlasov** [comment]
So if there are no more comments I sugest we can close this issue.
