### ISSUE TITLE
Create base docker images

### ISSUE THREAD

**Issue by demon-xxi** [pintostack/core#9]
Consider creating base Linux and java images.
Need to decide if they will be pushed to private repo during pinto setup or hosted on public docker hub. 

For example:
`Linux`
```
FROM alpine:3.3

RUN apk dd --update sed jq bash curl \
         && rm -rf /var/cache/apk/*
```

`java`
```
FROM develar/java:8u45

RUN apk dd --update sed jq bash curl \
         && rm -rf /var/cache/apk/*
```

**Comment by yvlasov** [comment]
Actualy this process is started but it requires all project refactoring...
The main parts are relativly optimal and inherited from basic source image so I sujest this issue can be closed.
While new more practical requests will apear.
THX
